# -*- coding: utf-8 -*-
"""case study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMEPVUwwoCBnAUfhYniJMdol9pxwYA95
"""

import numpy as np
import sympy as sp
data=[[32,400,20,95],
      [35,395,22,88],
      [38,390,25,80],
      [40,385,28,70],
      [42,380,30,60],
      [45,375,32,48]]
print("1.sensor readings:")
for i in data:
    print("readings:",i)
print("2.identify high temoerature:")
for i in data:
  if i[0]>40:
    print(i[0],"temperature high alter")
  else:
    print(i[0],"temperature normal")
print("3.identify low battery")
for i in data:
  if i[3]<50:
    print(i[3],"low battery alert")
  else:
    print("battery charge normal")
print("function based on status:")
def battery_status(C):
  if C>70:
    return "high"
  elif C>=50:
    return "medium"
  else:
    return "low"
print("status:",[battery_status(i[3]) for i in data])
print("TASK 2-ANALYSIS USING NUMPY")
d=np.array([
    [32,400,20,95],
  [35,395,22,88],
  [38,390,25,80],
  [40,385,28,70],
  [42,380,30,60],
  [45,375,32,48]
    ])
print("D=\n",d)
print("shape of the array:",d.shape)
print("average of each parameter")
print("temperature:",np.mean(d[:,0]))
print("voltage:",np.mean(d[:,1]))
print("current:",np.mean(d[:,2]))
print("charge:",np.mean(d[:,3]))
print("minimum and maximum temperature")
print("T_max:",np.max(d[:,0]))
print("T_min:",np.min(d[:,0]))
print("Voltage cloumn:",np.array(d[:,1]))
print("High_temperature Readings")
print("T>40=",d[d[:,0]>40])
print("Low_battery Readings")
print("C<50=",d[d[:,3]<50])
print("-----TASK 3-ANALYSIS USING LINEAR ALGEBRA-----")
A=np.array([[2,1],[1,3]])
X=np.array([[40],[25]])
Y=np.dot(A,X)
print("Y=",Y)
A_T=A.T
print("Transpose:\n",A_T)
det_A=np.linalg.det(A)
print("Determinant:",det_A)
inv_A=np.linalg.inv(A)
print("Inverse:\n",inv_A)
print("Solving 2x + y = 100,x + 3y = 120")
B=np.array([100,120])
sol=np.linalg.solve(A,B)
print("Solution:",sol)
x=sol[0]
y=sol[1]
print(f"solution:x={x:.2f},y={y:.2f}")
print("-----TASK-4:ANALYSIS USING CALCULUS-----")
t=sp.symbols('t')
dC_dt=100-2*t-(0.5)*(t**2)
deriv=sp.diff(dC_dt,t)
print("Rate of change dC/dt=",deriv)
t = sp.symbols('t')
C = 100 - 2*t - 0.5*t**2
dC_dt = sp.diff(C, t)
print(f"The rate of change is: {dC_dt}")
t2=dC_dt.subs(t,2)
t5=dC_dt.subs(t,5)
print("Discharge rate:")
print("at t=2",t2)
print("at t=4",t5)
if t2==t5:
  print("Constant rate")
elif t2<t5:
  print("Increasing rate")
else:
  print("Decreasing rate")
print("---Final Analysis and Decision---")