# -*- coding: utf-8 -*-
"""case study 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1toMX5hfxHjIafE9z30nfJzKWdHIcvAOC
"""

case-study

import pandas as pd
import numpy as np
data = {
    "Student": ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10"],
    "Study_Hours": [2, 3, 4, 5, 6, 7, 8, 4, 6, 9],
    "Attendance": [65, 70, 75, 80, 85, 90, 92, 78, 88, 95],
    "Assignment_Score": [55, 60, 65, 72, 78, 85, 88, 70, 80, 92],
    "Previous_Score": [58, 62, 68, 70, 76, 82, 86, 72, 79, 90],
    "Final_Score": [60, 64, 70, 75, 82, 88, 91, 74, 84, 94]
}
print("#task-1")
df = pd.DataFrame(data)
print("number of students:")
print(len(df))
print("column names:")
print(df.columns)
print("datatypes")
print(df.dtypes)
print("first five records:")
print(df.head(5))
print("last five records:")
print(df.tail(5))
print("# task-2")
print("AVERAGES:")
print(df.mean(numeric_only=True))
print("\nStudent with Highest Final Score:")
print(df.loc[df["Final_Score"].idxmax()])
print("\nStudent with Lowest Final Score:")
print(df.loc[df["Final_Score"].idxmin()])
print("attendance greater than 80%")
print(df[df['Attendance']>80]['Student'])
print("final score greater than 80")
print(df[df['Final_Score']>80]['Student'])
print(df.describe())
#task-3
Final_Scores=df['Final_Score'].values

print("mean:",np.mean(Final_Scores))
print("median:",np.median(Final_Scores))
print("maximum:",np.max(Final_Scores))
print("minimum:",np.min(Final_Scores))
print("standard deviation:",np.std(Final_Scores))
print("\n---Part D-Data Visualization---\n")
sns.scatterplot(x='Study_Hours',y='Final_Score',data=df)
plt.title('Study Hours vs Final Score')
plt.show()
sns.scatterplot(x='Attendance',y='Final_Score',data=df)
plt.title('Attendance vs Final Score')
plt.show()
sns.histplot(x='Final_Score',data=df)
plt.title('Distribution of final score')
plt.show()
sns.barplot(x='Student',y='Final_Score',data=df)
plt.title('Student wise final score')
plt.show()

print("\n---Part E-Linear Algebra---\n")
X = df[["Study_Hours", "Attendance", "Assignment_Score"]].values
print("Matrix:\n",X)
print("Shape of X:",X.shape)
X_T =X.T
print("Transpose of X:\n",X_T)
XTX=X_T@X
print("XTX:\n",XTX)
study_hours_vector=df['Study_Hours'].values
Final_Score_vector=df['Final_Score'].values
dot_Product=np.dot(study_hours_vector,Final_Score_vector)
print("Dot Product:",dot_Product)

print("\n---Part F-Calculus:Differentiation---\n")
def F(x):
  return 40 + 5*x - 0.2*x**2
def dF(x):
  return 5 - 0.4*x
print("Hours,F(x),F'(X)\n")
for x in range(1, 11):
  print(f"{x:<5}, {F(x):<5.1f}, {dF(x):.1f}")
optimal_hours=5/0.4
print(f"\nValue where F'(X)=0:{optimal_hours}.hours")

print("\n---Part G-Calculus:Integration---\n")
def L(X):
  return 5*x-0.2*x**2
x_vals = np.linspace(0, 5, 1000)
y_vals =5*x_vals-0.2*x_vals**2
area = np.trapezoid(y_vals, x_vals)
print(f"Integral 0 to 5 of L(x) dx (Numerical) = {area:.4f}")
print("Manual value = 54.1667")
print("Interpretation: Area represents total accumulated learning benefit from 0 to 5 study hours is 54.16")

print("\n--- Part H - Correlation ---\n")
corr = df.corr(numeric_only=True)
print(corr)

print("\nCorrelations with Final_Score:")
print(f"Study Hours: {corr.loc['Study_Hours','Final_Score']:.4f}")
print(f"Attendance: {corr.loc['Attendance','Final_Score']:.4f}")
print(f"Assignment_Score: {corr.loc['Assignment_Score','Final_Score']:.4f}")
print(f"Previous_Score: {corr.loc['Previous_Score','Final_Score']:.4f}")
plt.figure(figsize=(6,5))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

print("\n--- Part I - Linear Model Y = Xβ ---\n")
X= df[["Study_Hours", "Attendance", "Assignment_Score"]].values
Y = df["Final_Score"].values
X= np.column_stack((np.ones(len(X)), X))
beta = np.linalg.inv(X.T @ X) @ X.T @ Y
print(f"Coefficients beta = [b0, b1, b2, b3]:\n{beta}")
print(f"\nModel: Final = {beta[0]:.2f} + {beta[1]:.2f}*Study_Hours + {beta[2]:.2f}*Attendance + {beta[3]:.2f}*Assignment_Score")
print("\nInterpretation: b1,b2,b3 show how much Final Score increases for 1 unit increase in each input.")

print("\n--- Part J - Conclusion ---\n")
print(f"Average Final Score: {df['Final_Score'].mean():.2f}")
print(f"Variation (Std Dev): {df['Final_Score'].std():.2f} - moderate spread")
print(f"Highest Scorer: {df.loc[df['Final_Score'].idxmax(), 'Student']} with {df['Final_Score'].max()}")