# -*- coding: utf-8 -*-
"""Exception_Handling_and_Debugging_in_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2cwOOdjrVOvEB3yWi17_pogh2zoDx0o

# Exception Handling and Debugging in Python

✅ What exceptions are

⚠️ try, except, else, finally

✅ Raising exceptions manually

🔍 Basic debugging practices (print, traceback, pdb)

#✅ 1. What is an Exception?

Exceptions are errors that occur at runtime and stop the program unless handled.
"""

# Example: Division by zero error
# print(10 / 0)  # This will raise ZeroDivisionError

"""#⚠️ 2. Basic Try-Except Block"""

# Use try-except to handle errors gracefully

try:
    x = int(input("Enter a number: "))
    print("You entered:", x)
except ValueError:
    print("That was not a valid number!")

"""#🔁 3. Try-Except-Else-Finally Structure"""

try:
    num = int(input("Enter a number to divide 100: "))
    result = 100 / num
except ZeroDivisionError:
    print("Cannot divide by zero!")
except ValueError:
    print("Invalid input! Not a number.")
else:
    print("Result is:", result)
finally:
    print("Execution complete. This block always runs.")
ry:
    num = int(input("Enter a number to divide 100: "))
    result = 100 / num
except ZeroDivisionError:
    print("Cannot divide by zero!")
except ValueError:
    print("Invalid input! Not a number.")
else:
    print("Result is:", result)
finally:
    print("Execution complete. This block always runs.")

"""#🧨 4. Catching Multiple Exceptions"""

try:
    a = int("ten")  # Causes ValueError
    b = 10 / 0      # Causes ZeroDivisionError
except (ValueError, ZeroDivisionError) as e:
    print("An error occurred:", e)

"""#🚫 5. Raising Custom Exceptions"""

# Raise your own error using 'raise'

def check_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative!")
    else:
        print("Age is valid.")

try:
    check_age(-5)
except ValueError as e:
    print("Caught an exception:", e)

"""#🔍 6. DEBUGGING PRACTICES

🛠️ A. Using print() statements
"""

def divide(a, b):
    print(f"Dividing {a} by {b}")  # Debug info
    return a / b

print(divide(10, 2))  # Correct
# print(divide(10, 0))  # Uncomment to see the crash

"""#🛠️ B. Using traceback module (for detailed errors)"""

import traceback

try:
    result = 10 / 0
except Exception as e:
    print("Something went wrong.")
    traceback.print_exc()  # Prints detailed error stack

"""#🛠️ C. Using the Python Debugger (pdb)"""

# Uncomment to use the debugger
# import pdb

def calculate_total(price, quantity):
    # pdb.set_trace()  # Start interactive debugger here
    return price * quantity

print(calculate_total(50, 2))

"""#🧪 BONUS: Common Exceptions in Python

| Exception           | Description                           |
| ------------------- | ------------------------------------- |
| `ValueError`        | Wrong value type (e.g. int("abc"))    |
| `TypeError`         | Operation on incompatible types       |
| `ZeroDivisionError` | Division by zero                      |
| `IndexError`        | List index out of range               |
| `KeyError`          | Accessing non-existent dictionary key |
| `FileNotFoundError` | File does not exist                   |

#✅ Summary
Use try...except to handle runtime errors.

else: runs when no error occurs.

finally: always runs.

Use raise to throw your own exceptions.

Debug with print, traceback, or pdb.
"""



"""exceptional handling"""

try:
    x = int(input("Enter a number: "))
    print("You entered:", x)
except ValueError:
    print("That was not a valid number!")

try:
    num = int(input("Enter a number to divide 100: "))
    result = 100 / num
except ZeroDivisionError:
    print("Cannot divide by zero!")
except ValueError:
    print("Invalid input! Not a number.")
else:
    print("Result is:", result)
finally:
    print("Execution complete. This block always runs.")

try:
    a = int("ten")  # Causes ValueError
    b = 10 / 0      # Causes ZeroDivisionError
except (ValueError, ZeroDivisionError) as e:
    print("An error occurred:", e)

def check_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative!")
    else:
        print("Age is valid.")

try:
    check_age(-5)
except ValueError as e:
    print("Caught an exception:", e)

def divide(a, b):
    print(f"Dividing {a} by {b}")  # Debug info
    return a / b

print(divide(10, 3))  # Correct
# print(divide(10, 0))  # Uncomment to see the crash

import traceback

try:
    result = 10 / 0
except Exception as e:
    print("division not possible")
    traceback.print_exc()  # Prints detailed error stack



# Uncomment to use the debugger
# import pdb

def calculate_total(price, quantity):
    # pdb.set_trace()  # Start interactive debugger here
    return price * quantity

print(calculate_total(50, 3.5))