# -*- coding: utf-8 -*-
"""input&output formatted funs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBozVZCTv7boLrxBUZfVu_E39XOTIFT8
"""



"""input and output formatted functions"""

print("hello world")

if 5<2:
  print("five is greater than two")
else:
  print("less than")

name="stalin"
age=21
print(f"his name is {name} he is {age} years old")

name="stalin"
age=21
print("my name is {} i am {} years old".format(name,age))

name="stalin"
age=21
print("my name is %s and iam %d years old"%(name,age))

"""week1"""

print("Welcome to Python")

print(25)
print(50)

name = "Rahul"
print(name)

a = 20
b = 4
print()
print()

name = "Anjali"
age = 19

name = "Priya"

city = "Hyderabad"

name = "Kiran"

a = 5
b = 4

x = 2
print()

num = 25
print()

value = 15.522222
print(type(value))

name = "Asha"
marks = 92

print("Python", "Programming", "Language")

a = 10
b = 20
print("Sum =", a + b)

name ="Rahul"
print(name * 3)

age = input("Enter Age: ")

x = 10
y = 20

name = "Amit"
cgpa = 8.75