# -*- coding: utf-8 -*-
"""lists,_sets,_tuples,_and_dictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQrXkm0ltgBAAW5GcHy6KBHI4HfEi4Wg

#🧪 Python Practical: Lists, Sets, Tuples, Dictionaries
"""

# 🔹 1. LISTS
# A list is an ordered, mutable collection that allows duplicates

fruits = ['apple', 'banana', 'cherry', 'apple']
print("Original list:", fruits)

# Accessing elements by index
print("First fruit:", fruits[0])

# Adding an item
fruits.append('orange')
print("After appending:", fruits)

# Removing an item
fruits.remove('banana')
print("After removing banana:", fruits)

# List length
print("Number of fruits:", len(fruits))

# 🔹 2. TUPLES
# A tuple is an ordered, immutable collection that allows duplicates

dimensions = (10, 20, 30)
print("Tuple:", dimensions)

# Accessing elements
print("Second element:", dimensions[1])

# Tuples are immutable: can't add/remove
# dimensions[1] = 50 → This would raise an error

# 🔹 3. SETS
# A set is an unordered, mutable collection with NO duplicates

unique_numbers = {1, 2, 3, 2, 1}
print("Set (no duplicates):", unique_numbers)

# Adding elements
unique_numbers.add(4)
print("After adding 4:", unique_numbers)

# Removing elements
unique_numbers.remove(2)
print("After removing 2:", unique_numbers)

# Set operations
set_a = {1, 2, 3}
set_b = {3, 4, 5}
print("Union:", set_a | set_b)
print("Intersection:", set_a & set_b)
print("Difference (A - B):", set_a - set_b)

# 🔹 4. DICTIONARIES
# A dictionary stores key-value pairs (like a map or JSON object)

student = {
    'name': 'Alice',
    'age': 21,
    'course': 'Python'
}
print("Dictionary:", student)

# Access value by key
print("Student name:", student['name'])

# Add or update value
student['grade'] = 'A'
print("After adding grade:", student)

# Remove a key
del student['age']
print("After deleting age:", student)

# Loop through dictionary
for key, value in student.items():
    print(f"{key}: {value}")

# Bonus: Dictionary from two lists using zip()
keys = ['id', 'name', 'marks']
values = [101, 'John', 88]
student_info = dict(zip(keys, values))
print("Student Info from zip:", student_info)

"""#✅ Summary

| Data Type  | Ordered | Mutable | Duplicates | Example Syntax |
| ---------- | ------- | ------- | ---------- | -------------- |
| List       | ✅       | ✅       | ✅          | `['a', 'b']`   |
| Tuple      | ✅       | ❌       | ✅          | `('a', 'b')`   |
| Set        | ❌       | ✅       | ❌          | `{'a', 'b'}`   |
| Dictionary | ✅ keys  | ✅       | keys ❌     | `{'k': 'v'}`   |

"""