# -*- coding: utf-8 -*-
"""numpy.exp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQt92--dVlXUPd14NBV3gexx4YsL_WKz

numpy programs
"""

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

arr = np.zeros((2,2))
print(arr)

arr = np.arange(0,10)
print(arr)

arr = np.arange(1,16)
print(arr.reshape(3,5))

arr = np.array([[1,2,3,4], [4,5,6,7]])
print(arr.shape)
print(arr.size)



arr = np.linspace(1, 10, 3)
print(arr)



arr = np.eye(3)
print(arr)

arr = np.full((3, 3), 3)
print(arr)



arr = np.array([[1, 2],[4, 5]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)



arr = np.array([
    [[3, 2, 1],
     [6, 5, 4]],

    [[9, 8, 7],
     [12, 11, 10]]
])

print(arr)
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # (Layers, Rows, Columns)
print(arr.size)   # Total number of elements
print(arr[1])        # First layer
print(arr[1])        # Second layer
print(arr[1][0])     # Second row of first layer
print(arr[0][1][1])  # Element 9

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(3, 2)
print(new_arr)

arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])
new_arr_1 = np.reshape(arr,(3,3))
print(new_arr_1)

arr_3d = np.array([1,2,3,4,5,6,7,8])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:6])
print(arr[:3])
print(arr[3:])
print(arr[::3])

import numpy as np
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[0:1,1:2])
print(arr[2,:])
print(arr[:,1])

import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

import numpy as np

a = np.array([40,50,60])
b = np.array([2,5,6])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

import numpy as np
# Create a NumPy array
arr = np.array([1, 4, 9, 16, 25])
print("Original Array:", arr)
# Square Root
print("\nSquare Root:", np.sqrt(arr))
# Square
print("Square:", np.square(arr))
# Cube (Power 3)
print("Cube:", np.power(arr, 3))
# Absolute Value
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
# Exponential (e^x)
print("\nExponential:", np.exp(arr))
# Natural Logarithm
print("\nNatural Log:", np.log(arr))
# Base-10 Logarithm
print("Log Base 10:", np.log10(arr))
# Sine
print("\nSine:", np.sin(arr))
# Cosine
print("Cosine:", np.cos(arr))
# Tangent
print("Tangent:", np.tan(arr))
# Round Values
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
# Ceiling
print("Ceiling:", np.ceil(decimal))
# Floor
print("Floor:", np.floor(decimal))

import numpy as np

# Create a NumPy array
marks = np.array([75, 82, 90, 68, 95, 88, 79])

print("Original Array:", marks)
# Sort
print("Sorted Array:", np.sort(marks))
# Sum
print("\nSum:", np.sum(marks))

# Mean (Average)
print("Mean:", np.mean(marks))

# Median
print("Median:", np.median(marks))

# Maximum Value
print("Maximum:", np.max(marks))

# Minimum Value
print("Minimum:", np.min(marks))

# Range
print("Range:", np.ptp(marks))

# Standard Deviation
print("Standard Deviation:", np.std(marks))

# Variance
print("Variance:", np.var(marks))

# Index of Maximum Value
print("Index of Maximum:", np.argmax(marks))

# Index of Minimum Value
print("Index of Minimum:", np.argmin(marks))

# Percentiles
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

"""random"""

import numpy as np

# Random number
print(np.random.rand())

# Random numbers
print(np.random.rand(5))

# Random integers
print(np.random.randint(1, 11, 5))

# Random choice
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))

# Normal distribution
print(np.random.normal(50, 10, 5))

# Uniform distribution
print(np.random.uniform(10, 20, 5))

# Bernoulli random variable
print(np.random.binomial(1, 0.5))

# Binomial random variable
print(np.random.binomial(10, 0.7))

# Poisson random variable
print(np.random.poisson(4, 5))

# Exponential random variable

print(np.random.exponential(2, 5))