# -*- coding: utf-8 -*-
"""pandas.prog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQ_777kQI9kuaSZqBEciEXZMbRgIiipv
"""

pandas

import pandas as pd
import numpy as np

s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("\nSeries:")
print(s)

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print("\nDataFrame:")
print(df)

array = np.array([[2, 1], [4, 3], [6, 5]])
df_from_array = pd.DataFrame(array, columns=['Column1', 'Column2'])
print("\nDataFrame from NumPy array:")
print(df_from_array)

print("\nRow with label 2 using loc:")
print(df.loc[2])

print("\nFirst three rows using iloc:")
print(df.iloc[0:3])

print("\nSelect 'Name' column:")
print(df['Age'])

# Select multiple columns
print("\nSelect 'Name' and 'Salary' columns:")
print(df[['Name', 'Age']])

# Filter rows where a condition is true
print("\nRows where Age > 30:")
print(df[df['Age'] > 30])

data_dirty = {
    'Name': ['Alice', 'David', None, 'Bob'],
    'Age': [25, None, 35, 40],
    'Salary': [50000, 60000, None, 80000]
}
df_dirty = pd.DataFrame(data_dirty)
print("\nOriginal Dirty DataFrame:")
print(df_dirty)

print("\nDrop rows with any NaN values:")
print(df_dirty.dropna())

# Fill missing values with specified values
print("\nFill missing values with a specific value:")
print(df_dirty.fillna({'Name': 'Unknown', 'Age': df_dirty['Age'].mean(), 'Salary': 0}))

print("\nBoolean DataFrame for missing values:")
print(df_dirty.isnull())

print("\nRename columns:")
df_renamed = df.rename(columns={'Salary': 'BaseSalary'})
print(df_renamed)

print("\nSort by Age descending:")
print(df.sort_values(by='Age', ascending=False))

# Group by a derived boolean column and calculate mean
print("\nGroup by operation (average salary by age > 30 or not):")
df['AgeGroup'] = df['Age'] > 29
print(df.groupby('AgeGroup')['Salary'].mean())

