# -*- coding: utf-8 -*-
"""Probability & Statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sJz4xqYdeTzKle4n2GS1_VWamsAVKlj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance",
                   "IT", "HR", "Finance", "IT", "HR"],
    "Age": [22, 25, 28, 30, 24, 35, 40, 27, 29, 45,
            32, 26, 38, 31, 50],
    "Experience": [1, 2, 4, 6, 2, 10, 15, 3, 5, 18,
                   8, 3, 12, 7, 20],
    "Salary": [25000, 28000, 32000, 40000, 27000,
               55000, 80000, 35000, 38000, 95000,
               60000, 30000, 75000, 50000, 150000],
    "Performance_Score": [65, 70, 75, 80, 68,
                          85, 90, 78, 72, 95,
                          88, 74, 92, 82, 96],
    "Training_Completed": ["Yes", "No", "Yes", "Yes", "No",
                           "Yes", "Yes", "No", "Yes", "Yes",
                           "Yes", "No", "Yes", "Yes", "No"]
}

df = pd.DataFrame(data)
print(df)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance",
                   "IT", "HR", "Finance", "IT", "HR"],
    "Age": [22, 25, 28, 30, 24, 35, 40, 27, 29, 45,
            32, 26, 38, 31, 50],
    "Experience": [1, 2, 4, 6, 2, 10, 15, 3, 5, 18,
                   8, 3, 12, 7, 20],
    "Salary": [25000, 28000, 32000, 40000, 27000,
               55000, 80000, 35000, 38000, 95000,
               60000, 30000, 75000, 50000, 150000],
    "Performance_Score": [65, 70, 75, 80, 68,
                          85, 90, 78, 72, 95,
                          88, 74, 92, 82, 96],
    "Training_Completed": ["Yes", "No", "Yes", "Yes", "No",
                           "Yes", "Yes", "No", "Yes", "Yes",
                           "Yes", "No", "Yes", "Yes", "No"]
}

df = pd.DataFrame(data)
print(df)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "HR", "Finance",
                   "IT", "HR", "Finance", "IT", "HR"],
    "Age": [22, 25, 28, 30, 24, 35, 40, 27, 29, 45,
            32, 26, 38, 31, 50],
    "Experience": [1, 2, 4, 6, 2, 10, 15, 3, 5, 18,
                   8, 3, 12, 7, 20],
    "Salary": [25000, 28000, 32000, 40000, 27000,
               55000, 80000, 35000, 38000, 95000,
               60000, 30000, 75000, 50000, 150000],
    "Performance_Score": [65, 70, 75, 80, 68,
                          85, 90, 78, 72, 95,
                          88, 74, 92, 82, 96],
    "Training_Completed": ["Yes", "No", "Yes", "Yes", "No",
                           "Yes", "Yes", "No", "Yes", "Yes",
                           "Yes", "No", "Yes", "Yes", "No"]
}

df = pd.DataFrame(data)
print(df)
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.describe)
print(df["Department"].value_counts())
print(df["Training_Completed"].value_counts())
print(df.isnull().sum())
print(df["Age"].mean())
print(df["Experience"].mean())
print(df["Salary"].mean())
print(df["Performance_Score"].mean())
print(df["Age"].median())
print(df["Experience"].median())
print(df["Salary"].median())
print(df["Performance_Score"].median())
print(df["Age"].mode())
print(df["Experience"].mode())
print(df["Salary"].mode())
print(df["Performance_Score"].mode())
print(df["Age"].max() - df["Age"].min())
print(df["Age"].var())
print(df["Experience"].var())
print(df["Salary"].var())
print(df["Performance_Score"].var())
print(df["Age"].std())
print(df["Experience"].std())
print(df["Salary"].std())
print(df["Performance_Score"].std())
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print(df[["Age", "Experience", "Salary", "Performance_Score"]].skew())
plt.hist(df["Salary"], bins=6)
plt.xlabel("Salary")
plt.ylabel("Frequency")
plt.title("Salary Distribution")
plt.show()
plt.boxplot(df["Salary"])
plt.ylabel("Salary")
plt.title("Salary Box Plot")
plt.show()
summary = pd.DataFrame({
    "Mean": [
        df["Age"].mean(),
        df["Experience"].mean(),
        df["Salary"].mean(),
        df["Performance_Score"].mean()
    ],
    "Median": [
        df["Age"].median(),
        df["Experience"].median(),
        df["Salary"].median(),
        df["Performance_Score"].median()
    ],
    "Std_Deviation": [
        df["Age"].std(),
        df["Experience"].std(),
        df["Salary"].std(),
        df["Performance_Score"].std()
    ],
    "Skewness": [
        df["Age"].skew(),
        df["Experience"].skew(),
        df["Salary"].skew(),
        df["Performance_Score"].skew()
    ]
})

summary.index = ["Age", "Experience", "Salary", "Performance Score"]
print(summary)
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].median())
print(df.groupby("Department")["Salary"].std())
numeric_columns = df.select_dtypes(include=np.number).columns

for column in numeric_columns:
    print("\n", column)
    print("Mean:", df[column].mean())
    print("Median:", df[column].median())
    print("Mode:", df[column].mode().tolist())
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())
    print("Range:", df[column].max() - df[column].min())
    print("Variance:", df[column].var())
    print("Standard Deviation:", df[column].std())
    print("Q1:", df[column].quantile(0.25))
    print("Q3:", df[column].quantile(0.75))
    print("IQR:", df[column].quantile(0.75) -
          df[column].quantile(0.25))
    print("Skewness:", df[column].skew())

