# -*- coding: utf-8 -*-
"""Python_Core_Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4YOHAi0feHbladG7DuzSm1LG8AihmjL
"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}

# --- Task 1: Python Fundamentals, Lists, Tuples, Sets, Dictionaries, Indexing & Slicing ---
print("\n--- Task 1: Data Generation and Basic Structures ---")

# 1.1 Generate a list of 100 simulated sensor readings.
#    Each reading should be a tuple: (timestamp_str, device_id, device_type, location, value).
#    - timestamp_str: Format as 'YYYY-MM-DD HH:MM:SS'
#    - device_id: A unique ID for each reading (e.g., 'DEV001', 'DEV002', etc., up to 100 unique IDs).
#    - device_type: Randomly chosen from DEVICE_TYPES.
#    - location: Randomly chosen from LOCATIONS.
#    - value: Random float within READING_RANGES for its device_type (round to 2 decimal places).
# Store these in a list called 'raw_sensor_data'.

# Your code for Task 1.1 here:






# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.

# Your code for Task 1.2 here:




# 1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.
unique_locations=set()
for reading in raw_sensor_data:
  unique_locations.add(reading[3])
# Your code for Task 1.3 here:





# 1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:




# 1.5: Advanced Indexing and Slicing (Lists and Strings)
print("\n--- Task 1.5: Advanced Indexing and Slicing (Lists and Strings) ---")

# Let's use 'raw_sensor_data' and create a sample string for these tasks.
sample_string = "PythonProgrammingIsFun"

# 1.5.1 List Slicing: Extract elements from the 10th to the 20th (inclusive) from 'raw_sensor_data'.
#       Store the result in 'sliced_readings_1'.
#       Then, extract every 5th reading from 'raw_sensor_data' starting from the beginning.
#       Store the result in 'sliced_readings_2'.

# Your code for Task 1.5.1 here:



# 1.5.2 String Slicing: Extract the substring "Programming" from 'sample_string'.
#       Store the result in 'substring_1'.
#       Then, extract the substring "nohtyP" (the reverse of "Python") from 'sample_string' using slicing.
#       Store the result in 'substring_2'.

# Your code for Task 1.5.2 here:



# 1.5.3 Mixed Slicing: Access the 'device_type' of the 5th reading in 'raw_sensor_data' using indexing.
#       Store it in 'fifth_reading_device_type'.
#       Then, from 'fifth_reading_device_type', extract the last 6 characters (e.g., 'Sensor' from 'Temperature_Sensor').
#       Store it in 'device_type_suffix'.

# Your code for Task 1.5.3 here:




# --- Task 2: Writing and Using Functions in Python ---
print("\n--- Task 2: Function Definitions and Usage ---")

# 2.1 Write a function `get_readings_by_location(readings_list, target_location)`
#     that takes the 'raw_sensor_data' list and a 'target_location' string.
#     It should return a list of all readings (as tuples) for that specific location.

# Your code for Task 2.1 here:


# 2.2 Write a function `calculate_average_temperature(temp_data_list)`
#     that takes the 'temperature_readings' list (list of dictionaries).
#     It should calculate and return the average temperature. Return 0.0 if the list is empty.

# Your code for Task 2.2 here:



# 2.3 Write a function `generate_report_line(reading_dict)`
#     that takes a single temperature reading dictionary.
#     It should return a formatted string like:
#     "[{timestamp}] Device {device_id} at {location}: {temperature_celsius}°C"

# Your code for Task 2.3 here:



# --- Task 3: Working with Core Python Libraries (os, datetime, random) ---
print("\n--- Task 3: Core Library Usage ---")

# 3.1 Use the `os` module to create a new directory named 'sensor_reports'
#     in the current working directory, if it doesn't already exist.

# Your code for Task 3.1 here:
reports_dir = 'sensor_reports'
if not os.path.exists(reports_dir):
    os.makedirs(reports_dir)
    print(f"\nDirectory '{reports_dir}' created.")
else:
    print(f"\nDirectory '{reports_dir}' already exists.")


# 3.2 Calculate the duration between the first and last timestamp in 'raw_sensor_data'.
#     Convert string timestamps to datetime objects first.
#     Print the duration in days, hours, and minutes.

# Your code for Task 3.2 here:
if len(raw_sensor_data) > 1:
    first_timestamp_str = raw_sensor_data[0][0]
    last_timestamp_str = raw_sensor_data[-1][0]

    # Convert string to datetime object
    # The format string must exactly match the timestamp string
    date_format = '%Y-%m-%d %H:%M:%S'
    first_dt = datetime.datetime.strptime(first_timestamp_str, date_format)
    last_dt = datetime.datetime.strptime(last_timestamp_str, date_format)

    duration = last_dt - first_dt

    days = duration.days
    seconds = duration.total_seconds()
    hours = int(seconds // 3600) % 24 # Calculate remaining hours after full days
    minutes = int((seconds % 3600) // 60) # Calculate remaining minutes after full hours

    print(f"\nDuration of data collection: {days} days, {hours} hours, {minutes} minutes.")
else:
    print("\nNot enough data to calculate duration.")


# 3.3 Generate a list of 5 random integer values between 100 and 200 (inclusive)
#     using the `random` module. Store it in 'random_values'.

# Your code for Task 3.3 here:



# --- Task 4: File Handling in Python ---
print("\n--- Task 4: File I/O ---")

# 4.1 Write all 'temperature_readings' to a file named 'sensor_reports/temperature_report.txt'.
#     Each line in the file should be generated using the `generate_report_line` function.

# Your code for Task 4.1 here:
report_filename = os.path.join(reports_dir, 'temperature_report.txt')
try:
    with open(report_filename, 'w') as f:
        for reading_dict in temperature_readings:
            line = generate_report_line(reading_dict)
            f.write(line + '\n')
    print(f"\nTemperature report written to '{report_filename}'.")
except IOError as e:
    print(f"\nError writing file '{report_filename}': {e}")


# 4.2 Read the content of 'sensor_reports/temperature_report.txt' back into a list of strings
#     named 'read_report_lines'. Print the first 3 lines.

# Your code for Task 4.2 here:





print("\n--- Exercise Complete! ---")
print("Great job completing the intermediate Python exercise.")
print("Review your code and outputs to ensure correctness and understanding of all concepts.")
print("Consider adding more complex scenarios or user inputs for further practice.")

"""Generate a list of 100 simulated sensor readings.
#    Each reading should be a tuple: (timestamp_str, device_id, device_type, location, value).
#    - timestamp_str: Format as 'YYYY-MM-DD HH:MM:SS'
#    - device_id: A unique ID for each reading (e.g., 'DEV001', 'DEV002', etc., up to 100 unique IDs).
#    - device_type: Randomly chosen from DEVICE_TYPES.
#    - location: Randomly chosen from LOCATIONS.
#    - value: Random float within READING_RANGES for its device_type (round to 2 decimal places).
# Store these in a list called 'raw_sensor_data'.
"""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
DEVICE_TYPES = ["Temperature_Sensor", "Humidity_Sensor", "Pressure_Sensor", "Light_Sensor"]
LOCATIONS = ["Lab1", "Lab2", "OfficeA", "OfficeB", "Warehouse"]
READING_RANGES = {
    "Temperature_Sensor": (18.0, 30.0),  # Celsius
    "Humidity_Sensor": (30.0, 80.0),     # Percentage
    "Pressure_Sensor": (980.0, 1030.0),   # hPa
    "Light_Sensor": (100, 1000)          # Lux
}

# --- Task 1: Python Fundamentals, Lists, Tuples, Sets, Dictionaries, Indexing & Slicing ---
print("\n--- Task 1: Data Generation and Basic Structures ---")

# 1.1 Generate a list of 100 simulated sensor readings.
# Set a base time for the timestamps (e.g., starting from now)
base_time = datetime.datetime.now()

raw_sensor_data = []
for i in range(1, 101):
    # Generate unique device ID padded with zeros (DEV001, DEV002, etc.)
    device_id = f"DEV{i:03d}"

    # Pick a random device type and location
    device_type = random.choice(DEVICE_TYPES)
    location = random.choice(LOCATIONS)

    # Get the value range and generate a rounded random float
    min_val, max_val = READING_RANGES[device_type]
    value = round(random.uniform(min_val, max_val), 2)

    # Create a unique timestamp incremented by 1 minute for each reading
    timestamp = base_time + datetime.timedelta(minutes=i)
    timestamp_str = timestamp.strftime("%Y-%m-%d %H:%M:%S")

    # Append the constructed tuple to the list
    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))

# Verify the generation by printing the first 3 elements
print(f"Successfully generated {len(raw_sensor_data)} sensor readings.")
print("Sample data (First 3 items):")
for reading in raw_sensor_data[:5]:
    print(reading)

""" From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.

"""

# --- Global Data for the Exercise (Simulated Data) ---
DEVICE_TYPES = ["Temperature Sensor", "Humidity Sensor", "Pressure Sensor", "Light Sensor"]
LOCATIONS = ["Lab1", "Lab2", "OfficeA", "OfficeB", "Warehouse"]
READING_RANGES = {
    "Temperature_Sensor": (18.0, 30.0),  # Celsius
    "Humidity_Sensor": (30.0, 80.0),     # Percentage
    "Pressure_Sensor": (980.0, 1030.0),  # hPa
    "Light_Sensor": (100, 1000)          # Lux
}

# Simulated raw sensor data based on your dictionary structure
raw_sensor_data = [
    {
        "timestamp": "2026-07-20T14:30:00Z",
        "device_type": "Temperature_Sensor",
        "device_id": "TEMP_01",
        "location": "Lab1",
        "value": 22.5
    }
]

temperature_readings = []

# Corrected iteration block
for reading in raw_sensor_data:
    # 1. Fixed key typo from 'devicetype' to 'device_type'
    # 2. Fixed string from 'Temperature Sensor' to match 'Temperature_Sensor' with an underscore
    if reading["device_type"] == "Temperature_Sensor":
        # Extract and rename the necessary keys
        temp_reading = {
            "timestamp": reading["timestamp"],
            "device_id": reading["device_id"],
            "location": reading["location"],
            "temperature_celsius": reading["value"]  # Mapping 'value' to 'temperature_celsius'
        }
        temperature_readings.append(temp_reading)

# Print results to verify
print("Extracted Temperature Readings:")
print(temperature_readings)

"""Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'."""

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
DEVICE_TYPES = ["Temperature_Sensor", "Humidity_Sensor", "Pressure_Sensor", "Light_Sensor"]
LOCATIONS = ["Lab1", "Lab2", "OfficeA", "OfficeB", "Warehouse"]
READING_RANGES = {
    "Temperature_Sensor": (18.0, 30.0),  # Celsius
    "Humidity_Sensor": (30.0, 80.0),     # Percentage
    "Pressure_Sensor": (980.0, 1030.0),   # hPa
    "Light_Sensor": (100, 1000)          # Lux
}
#1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.
unique_locations=set()
for reading in raw_sensor_data:
  unique_locations.add(reading[3])
# Your code for Task 1.3 here: